name: Build and Publish to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: cloudflare

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: Build the app
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: 3d8b9791e512cae3eb6c72a59a136b2444706
          accountId: b39121ff87d896114dbae7a2b0e61e
          projectName: white-label-github-actions
          directory: ../../static/
          # Optional: Enable this if you want to have GitHub Deployments triggered
