name: Build and Publish to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Set Cloudflare Pages environment
        run: echo "CF_PAGES_SITE=${{ env.CF_PAGES_SITE }}" >> $GITHUB_ENV

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/cloudflare-pages-action@1.8.0
        with:
          apiToken: 3d8b9791e512cae3eb6c72a59a136b2444706 
          organizationId: ${{ secrets.CF_ORGANIZATION_ID }}
          script: npm ci && npm run build
          site: ${{ env.CF_PAGES_SITE }}
